using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RethusSalud.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AgregarCatalogoPaisesYMunicipios : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                INSERT INTO Paises (Nombre) VALUES
                ('Afganistán'),
                ('Albania'),
                ('Alemania'),
                ('Andorra'),
                ('Angola'),
                ('Antigua y Barbuda'),
                ('Arabia Saudita'),
                ('Argelia'),
                ('Argentina'),
                ('Armenia'),
                ('Australia'),
                ('Austria'),
                ('Azerbaiyán'),
                ('Bahamas'),
                ('Bangladés'),
                ('Barbados'),
                ('Baréin'),
                ('Bélgica'),
                ('Belice'),
                ('Benín'),
                ('Bielorrusia'),
                ('Birmania (Myanmar)'),
                ('Bolivia'),
                ('Bosnia y Herzegovina'),
                ('Botsuana'),
                ('Brasil'),
                ('Brunéi'),
                ('Bulgaria'),
                ('Burkina Faso'),
                ('Burundi'),
                ('Bután'),
                ('Cabo Verde'),
                ('Camboya'),
                ('Camerún'),
                ('Canadá'),
                ('Catar'),
                ('Chad'),
                ('Chile'),
                ('China'),
                ('Chipre'),
                ('Ciudad del Vaticano'),
                ('Comoras'),
                ('Corea del Norte'),
                ('Corea del Sur'),
                ('Costa de Marfil'),
                ('Costa Rica'),
                ('Croacia'),
                ('Cuba'),
                ('Dinamarca'),
                ('Dominica'),
                ('Ecuador'),
                ('Egipto'),
                ('El Salvador'),
                ('Emiratos Árabes Unidos'),
                ('Eritrea'),
                ('Eslovaquia'),
                ('Eslovenia'),
                ('España'),
                ('Estados Unidos'),
                ('Estonia'),
                ('Esuatini'),
                ('Etiopía'),
                ('Filipinas'),
                ('Finlandia'),
                ('Fiyi'),
                ('Francia'),
                ('Gabón'),
                ('Gambia'),
                ('Georgia'),
                ('Ghana'),
                ('Granada'),
                ('Grecia'),
                ('Guatemala'),
                ('Guinea'),
                ('Guinea-Bisáu'),
                ('Guinea Ecuatorial'),
                ('Guyana'),
                ('Haití'),
                ('Honduras'),
                ('Hungría'),
                ('India'),
                ('Indonesia'),
                ('Irak'),
                ('Irán'),
                ('Irlanda'),
                ('Islandia'),
                ('Islas Marshall'),
                ('Islas Salomón'),
                ('Israel'),
                ('Italia'),
                ('Jamaica'),
                ('Japón'),
                ('Jordania'),
                ('Kazajistán'),
                ('Kenia'),
                ('Kirguistán'),
                ('Kiribati'),
                ('Kuwait'),
                ('Laos'),
                ('Lesoto'),
                ('Letonia'),
                ('Líbano'),
                ('Liberia'),
                ('Libia'),
                ('Liechtenstein'),
                ('Lituania'),
                ('Luxemburgo'),
                ('Macedonia del Norte'),
                ('Madagascar'),
                ('Malasia'),
                ('Malaui'),
                ('Maldivas'),
                ('Malí'),
                ('Malta'),
                ('Marruecos'),
                ('Mauricio'),
                ('Mauritania'),
                ('México'),
                ('Micronesia'),
                ('Moldavia'),
                ('Mónaco'),
                ('Mongolia'),
                ('Montenegro'),
                ('Mozambique'),
                ('Namibia'),
                ('Nauru'),
                ('Nepal'),
                ('Nicaragua'),
                ('Níger'),
                ('Nigeria'),
                ('Noruega'),
                ('Nueva Zelanda'),
                ('Omán'),
                ('Países Bajos'),
                ('Pakistán'),
                ('Palaos'),
                ('Palestina'),
                ('Panamá'),
                ('Papúa Nueva Guinea'),
                ('Paraguay'),
                ('Perú'),
                ('Polonia'),
                ('Portugal'),
                ('Reino Unido'),
                ('República Centroafricana'),
                ('República Checa'),
                ('República del Congo'),
                ('República Democrática del Congo'),
                ('República Dominicana'),
                ('Ruanda'),
                ('Rumanía'),
                ('Rusia'),
                ('Samoa'),
                ('San Cristóbal y Nieves'),
                ('San Marino'),
                ('San Vicente y las Granadinas'),
                ('Santa Lucía'),
                ('Santo Tomé y Príncipe'),
                ('Senegal'),
                ('Serbia'),
                ('Seychelles'),
                ('Sierra Leona'),
                ('Singapur'),
                ('Siria'),
                ('Somalia'),
                ('Sri Lanka'),
                ('Sudáfrica'),
                ('Sudán'),
                ('Sudán del Sur'),
                ('Suecia'),
                ('Suiza'),
                ('Surinam'),
                ('Tailandia'),
                ('Tanzania'),
                ('Tayikistán'),
                ('Timor Oriental'),
                ('Togo'),
                ('Tonga'),
                ('Trinidad y Tobago'),
                ('Túnez'),
                ('Turkmenistán'),
                ('Turquía'),
                ('Tuvalu'),
                ('Ucrania'),
                ('Uganda'),
                ('Uruguay'),
                ('Uzbekistán'),
                ('Vanuatu'),
                ('Venezuela'),
                ('Vietnam'),
                ('Yemen'),
                ('Yibuti'),
                ('Zambia'),
                ('Zimbabue');
            ");

            migrationBuilder.Sql(@"
                INSERT INTO Municipios (DepartamentoId, Nombre) VALUES
                (2, 'Abejorral'),
                (2, 'Abriaquí'),
                (2, 'Alejandría'),
                (2, 'Amagá'),
                (2, 'Amalfi'),
                (2, 'Andes'),
                (2, 'Angelópolis'),
                (2, 'Angostura'),
                (2, 'Anorí'),
                (2, 'Santafé de Antioquia'),
                (2, 'Anza'),
                (2, 'Apartadó'),
                (2, 'Arboletes'),
                (2, 'Argelia'),
                (2, 'Armenia'),
                (2, 'Barbosa'),
                (2, 'Belmira'),
                (2, 'Bello'),
                (2, 'Betania'),
                (2, 'Betulia'),
                (2, 'Ciudad Bolívar'),
                (2, 'Briceño'),
                (2, 'Buriticá'),
                (2, 'Cáceres'),
                (2, 'Caicedo'),
                (2, 'Caldas'),
                (2, 'Campamento'),
                (2, 'Cañasgordas'),
                (2, 'Caracolí'),
                (2, 'Caramanta'),
                (2, 'Carepa'),
                (2, 'El Carmen de Viboral'),
                (2, 'Carolina'),
                (2, 'Caucasia'),
                (2, 'Chigorodó'),
                (2, 'Cisneros'),
                (2, 'Cocorná'),
                (2, 'Concepción'),
                (2, 'Concordia'),
                (2, 'Copacabana'),
                (2, 'Dabeiba'),
                (2, 'Don Matías'),
                (2, 'Ebéjico'),
                (2, 'El Bagre'),
                (2, 'Entrerrios'),
                (2, 'Envigado'),
                (2, 'Fredonia'),
                (2, 'Frontino'),
                (2, 'Giraldo'),
                (2, 'Girardota'),
                (2, 'Gómez Plata'),
                (2, 'Granada'),
                (2, 'Guadalupe'),
                (2, 'Guarne'),
                (2, 'Guatapé'),
                (2, 'Heliconia'),
                (2, 'Hispania'),
                (2, 'Itagui'),
                (2, 'Ituango'),
                (2, 'Jardín'),
                (2, 'Jericó'),
                (2, 'La Ceja'),
                (2, 'La Estrella'),
                (2, 'La Pintada'),
                (2, 'La Unión'),
                (2, 'Liborina'),
                (2, 'Maceo'),
                (2, 'Marinilla'),
                (2, 'Montebello'),
                (2, 'Murindó'),
                (2, 'Mutatá'),
                (2, 'Nariño'),
                (2, 'Necoclí'),
                (2, 'Nechí'),
                (2, 'Olaya'),
                (2, 'Peñol'),
                (2, 'Peque'),
                (2, 'Pueblorrico'),
                (2, 'Puerto Berrío'),
                (2, 'Puerto Nare'),
                (2, 'Puerto Triunfo'),
                (2, 'Remedios'),
                (2, 'Retiro'),
                (2, 'Rionegro'),
                (2, 'Sabanalarga'),
                (2, 'Sabaneta'),
                (2, 'Salgar'),
                (2, 'San Andrés de Cuerquía'),
                (2, 'San Carlos'),
                (2, 'San Francisco'),
                (2, 'San Jerónimo'),
                (2, 'San José de La Montaña'),
                (2, 'San Juan de Urabá'),
                (2, 'San Luis'),
                (2, 'San Pedro'),
                (2, 'San Pedro de Uraba'),
                (2, 'San Rafael'),
                (2, 'San Roque'),
                (2, 'San Vicente'),
                (2, 'Santa Bárbara'),
                (2, 'Santa Rosa de Osos'),
                (2, 'Santo Domingo'),
                (2, 'El Santuario'),
                (2, 'Segovia'),
                (2, 'Sonsón'),
                (2, 'Sopetrán'),
                (2, 'Támesis'),
                (2, 'Tarazá'),
                (2, 'Tarso'),
                (2, 'Titiribí'),
                (2, 'Toledo'),
                (2, 'Turbo'),
                (2, 'Uramita'),
                (2, 'Urrao'),
                (2, 'Valdivia'),
                (2, 'Valparaíso'),
                (2, 'Vegachí'),
                (2, 'Venecia'),
                (2, 'Vigía del Fuerte'),
                (2, 'Yalí'),
                (2, 'Yarumal'),
                (2, 'Yolombó'),
                (2, 'Yondó'),
                (2, 'Zaragoza'),
                (4, 'Baranoa'),
                (4, 'Campo de La Cruz'),
                (4, 'Candelaria'),
                (4, 'Galapa'),
                (4, 'Juan de Acosta'),
                (4, 'Luruaco'),
                (4, 'Malambo'),
                (4, 'Manatí'),
                (4, 'Palmar de Varela'),
                (4, 'Piojó'),
                (4, 'Polonuevo'),
                (4, 'Ponedera'),
                (4, 'Puerto Colombia'),
                (4, 'Repelón'),
                (4, 'Sabanagrande'),
                (4, 'Sabanalarga'),
                (4, 'Santa Lucía'),
                (4, 'Santo Tomás'),
                (4, 'Soledad'),
                (4, 'Suan'),
                (4, 'Tubará'),
                (4, 'Usiacurí'),
                (5, 'Cartagena'),
                (5, 'Achí'),
                (5, 'Altos del Rosario'),
                (5, 'Arenal'),
                (5, 'Arjona'),
                (5, 'Arroyohondo'),
                (5, 'Barranco de Loba'),
                (5, 'Calamar'),
                (5, 'Cantagallo'),
                (5, 'Cicuco'),
                (5, 'Córdoba'),
                (5, 'Clemencia'),
                (5, 'El Carmen de Bolívar'),
                (5, 'El Guamo'),
                (5, 'El Peñón'),
                (5, 'Hatillo de Loba'),
                (5, 'Magangué'),
                (5, 'Mahates'),
                (5, 'Margarita'),
                (5, 'María la Baja'),
                (5, 'Montecristo'),
                (5, 'Mompós'),
                (5, 'Morales'),
                (5, 'Norosí'),
                (5, 'Pinillos'),
                (5, 'Regidor'),
                (5, 'Río Viejo'),
                (5, 'San Cristóbal'),
                (5, 'San Estanislao'),
                (5, 'San Fernando'),
                (5, 'San Jacinto'),
                (5, 'San Jacinto del Cauca'),
                (5, 'San Juan Nepomuceno'),
                (5, 'San Martín de Loba'),
                (5, 'San Pablo de Borbur'),
                (5, 'Santa Catalina'),
                (5, 'Santa Rosa'),
                (5, 'Santa Rosa del Sur'),
                (5, 'Simití'),
                (5, 'Soplaviento'),
                (5, 'Talaigua Nuevo'),
                (5, 'Tiquisio'),
                (5, 'Turbaco'),
                (5, 'Turbaná'),
                (5, 'Villanueva'),
                (5, 'Zambrano'),
                (6, 'Almeida'),
                (6, 'Aquitania'),
                (6, 'Arcabuco'),
                (6, 'Belén'),
                (6, 'Berbeo'),
                (6, 'Betéitiva'),
                (6, 'Boavita'),
                (6, 'Boyacá'),
                (6, 'Briceño'),
                (6, 'Buena Vista'),
                (6, 'Busbanzá'),
                (6, 'Caldas'),
                (6, 'Campohermoso'),
                (6, 'Cerinza'),
                (6, 'Chinavita'),
                (6, 'Chiquinquirá'),
                (6, 'Chiscas'),
                (6, 'Chita'),
                (6, 'Chitaraque'),
                (6, 'Chivatá'),
                (6, 'Ciénega'),
                (6, 'Cómbita'),
                (6, 'Coper'),
                (6, 'Corrales'),
                (6, 'Covarachía'),
                (6, 'Cubará'),
                (6, 'Cucaita'),
                (6, 'Cuítiva'),
                (6, 'Chíquiza'),
                (6, 'Chivor'),
                (6, 'Duitama'),
                (6, 'El Cocuy'),
                (6, 'El Espino'),
                (6, 'Firavitoba'),
                (6, 'Floresta'),
                (6, 'Gachantivá'),
                (6, 'Gameza'),
                (6, 'Garagoa'),
                (6, 'Guacamayas'),
                (6, 'Guateque'),
                (6, 'Guayatá'),
                (6, 'Güicán'),
                (6, 'Iza'),
                (6, 'Jenesano'),
                (6, 'Jericó'),
                (6, 'Labranzagrande'),
                (6, 'La Capilla'),
                (6, 'La Victoria'),
                (6, 'La Uvita'),
                (6, 'Villa de Leyva'),
                (6, 'Macanal'),
                (6, 'Maripí'),
                (6, 'Miraflores'),
                (6, 'Mongua'),
                (6, 'Monguí'),
                (6, 'Moniquirá'),
                (6, 'Motavita'),
                (6, 'Muzo'),
                (6, 'Nobsa'),
                (6, 'Nuevo Colón'),
                (6, 'Oicatá'),
                (6, 'Otanche'),
                (6, 'Pachavita'),
                (6, 'Páez'),
                (6, 'Paipa'),
                (6, 'Pajarito'),
                (6, 'Panqueba'),
                (6, 'Pauna'),
                (6, 'Paya'),
                (6, 'Paz de Río'),
                (6, 'Pesca'),
                (6, 'Pisba'),
                (6, 'Puerto Boyacá'),
                (6, 'Quípama'),
                (6, 'Ramiriquí'),
                (6, 'Ráquira'),
                (6, 'Rondón'),
                (6, 'Saboyá'),
                (6, 'Sáchica'),
                (6, 'Samacá'),
                (6, 'San Eduardo'),
                (6, 'San José de Pare'),
                (6, 'San Luis de Gaceno'),
                (6, 'San Mateo'),
                (6, 'San Miguel de Sema'),
                (6, 'San Pablo de Borbur'),
                (6, 'Santana'),
                (6, 'Santa María'),
                (6, 'Santa Rosa de Viterbo'),
                (6, 'Santa Sofía'),
                (6, 'Sativanorte'),
                (6, 'Sativasur'),
                (6, 'Siachoque'),
                (6, 'Soatá'),
                (6, 'Socotá'),
                (6, 'Socha'),
                (6, 'Sogamoso'),
                (6, 'Somondoco'),
                (6, 'Sora'),
                (6, 'Sotaquirá'),
                (6, 'Soracá'),
                (6, 'Susacón'),
                (6, 'Sutamarchán'),
                (6, 'Sutatenza'),
                (6, 'Tasco'),
                (6, 'Tenza'),
                (6, 'Tibaná'),
                (6, 'Tibasosa'),
                (6, 'Tinjacá'),
                (6, 'Tipacoque'),
                (6, 'Toca'),
                (6, 'Togüí'),
                (6, 'Tópaga'),
                (6, 'Tota'),
                (6, 'Tununguá'),
                (6, 'Turmequé'),
                (6, 'Tuta'),
                (6, 'Tutazá'),
                (6, 'Umbita'),
                (6, 'Ventaquemada'),
                (6, 'Viracachá'),
                (6, 'Zetaquira'),
                (7, 'Aguadas'),
                (7, 'Anserma'),
                (7, 'Aranzazu'),
                (7, 'Belalcázar'),
                (7, 'Chinchiná'),
                (7, 'Filadelfia'),
                (7, 'La Dorada'),
                (7, 'La Merced'),
                (7, 'Manzanares'),
                (7, 'Marmato'),
                (7, 'Marquetalia'),
                (7, 'Marulanda'),
                (7, 'Neira'),
                (7, 'Norcasia'),
                (7, 'Pácora'),
                (7, 'Palestina'),
                (7, 'Pensilvania'),
                (7, 'Riosucio'),
                (7, 'Risaralda'),
                (7, 'Salamina'),
                (7, 'Samaná'),
                (7, 'San José'),
                (7, 'Supía'),
                (7, 'Victoria'),
                (7, 'Villamaría'),
                (7, 'Viterbo'),
                (8, 'Albania'),
                (8, 'Belén de Los Andaquies'),
                (8, 'Cartagena del Chairá'),
                (8, 'Curillo'),
                (8, 'El Doncello'),
                (8, 'El Paujil'),
                (8, 'La Montañita'),
                (8, 'Milán'),
                (8, 'Morelia'),
                (8, 'Puerto Rico'),
                (8, 'San José del Fragua'),
                (8, 'San Vicente del Caguán'),
                (8, 'Solano'),
                (8, 'Solita'),
                (8, 'Valparaíso'),
                (10, 'Almaguer'),
                (10, 'Argelia'),
                (10, 'Balboa'),
                (10, 'Bolívar'),
                (10, 'Buenos Aires'),
                (10, 'Cajibío'),
                (10, 'Caldono'),
                (10, 'Caloto'),
                (10, 'Corinto'),
                (10, 'El Tambo'),
                (10, 'Florencia'),
                (10, 'Guachené'),
                (10, 'Guapi'),
                (10, 'Inzá'),
                (10, 'Jambaló'),
                (10, 'La Sierra'),
                (10, 'La Vega'),
                (10, 'López'),
                (10, 'Mercaderes'),
                (10, 'Miranda'),
                (10, 'Morales'),
                (10, 'Padilla'),
                (10, 'Páez'),
                (10, 'Patía'),
                (10, 'Piamonte'),
                (10, 'Piendamó'),
                (10, 'Puerto Tejada'),
                (10, 'Puracé'),
                (10, 'Rosas'),
                (10, 'San Sebastián'),
                (10, 'Santander de Quilichao'),
                (10, 'Santa Rosa'),
                (10, 'Silvia'),
                (10, 'Sotara'),
                (10, 'Suárez'),
                (10, 'Sucre'),
                (10, 'Timbío'),
                (10, 'Timbiquí'),
                (10, 'Toribio'),
                (10, 'Totoró'),
                (10, 'Villa Rica'),
                (11, 'Manaure'),
                (13, 'Ayapel'),
                (13, 'Buenavista'),
                (13, 'Canalete'),
                (13, 'Cereté'),
                (13, 'Chimá'),
                (13, 'Chinú'),
                (13, 'Ciénaga de Oro'),
                (13, 'Cotorra'),
                (13, 'La Apartada'),
                (13, 'Lorica'),
                (13, 'Los Córdobas'),
                (13, 'Momil'),
                (13, 'Montelíbano'),
                (13, 'Moñitos'),
                (13, 'Planeta Rica'),
                (13, 'Pueblo Nuevo'),
                (13, 'Puerto Escondido'),
                (13, 'Puerto Libertador'),
                (13, 'Purísima'),
                (13, 'Sahagún'),
                (13, 'San Andrés Sotavento'),
                (13, 'San Antero'),
                (13, 'San Bernardo del Viento'),
                (13, 'San Carlos'),
                (13, 'San José de Uré'),
                (13, 'San Pelayo'),
                (13, 'Tierralta'),
                (13, 'Tuchín'),
                (13, 'Valencia'),
                (14, 'Agua de Dios'),
                (14, 'Albán'),
                (14, 'Anapoima'),
                (14, 'Anolaima'),
                (14, 'Arbeláez'),
                (14, 'Beltrán'),
                (14, 'Bituima'),
                (14, 'Bojacá'),
                (14, 'Cabrera'),
                (14, 'Cachipay'),
                (14, 'Cajicá'),
                (14, 'Caparrapí'),
                (14, 'Caqueza'),
                (14, 'Carmen de Carupa'),
                (14, 'Chaguaní'),
                (14, 'Chía'),
                (14, 'Chipaque'),
                (14, 'Choachí'),
                (14, 'Chocontá'),
                (14, 'Cogua'),
                (14, 'Cota'),
                (14, 'Cucunubá'),
                (14, 'El Colegio'),
                (14, 'El Peñón'),
                (14, 'El Rosal'),
                (14, 'Facatativá'),
                (14, 'Fomeque'),
                (14, 'Fosca'),
                (14, 'Funza'),
                (14, 'Fúquene'),
                (14, 'Fusagasugá'),
                (14, 'Gachala'),
                (14, 'Gachancipá'),
                (14, 'Gachetá'),
                (14, 'Gama'),
                (14, 'Girardot'),
                (14, 'Granada'),
                (14, 'Guachetá'),
                (14, 'Guaduas'),
                (14, 'Guasca'),
                (14, 'Guataquí'),
                (14, 'Guatavita'),
                (14, 'Guayabal de Siquima'),
                (14, 'Guayabetal'),
                (14, 'Gutiérrez'),
                (14, 'Jerusalén'),
                (14, 'Junín'),
                (14, 'La Calera'),
                (14, 'La Mesa'),
                (14, 'La Palma'),
                (14, 'La Peña'),
                (14, 'La Vega'),
                (14, 'Lenguazaque'),
                (14, 'Macheta'),
                (14, 'Madrid'),
                (14, 'Manta'),
                (14, 'Medina'),
                (14, 'Mosquera'),
                (14, 'Nariño'),
                (14, 'Nemocón'),
                (14, 'Nilo'),
                (14, 'Nimaima'),
                (14, 'Nocaima'),
                (14, 'Venecia'),
                (14, 'Pacho'),
                (14, 'Paime'),
                (14, 'Pandi'),
                (14, 'Paratebueno'),
                (14, 'Pasca'),
                (14, 'Puerto Salgar'),
                (14, 'Pulí'),
                (14, 'Quebradanegra'),
                (14, 'Quetame'),
                (14, 'Quipile'),
                (14, 'Apulo'),
                (14, 'Ricaurte'),
                (14, 'San Antonio del Tequendama'),
                (14, 'San Bernardo'),
                (14, 'San Cayetano'),
                (14, 'San Francisco'),
                (14, 'San Juan de Río Seco'),
                (14, 'Sasaima'),
                (14, 'Sesquilé'),
                (14, 'Sibaté'),
                (14, 'Silvania'),
                (14, 'Simijaca'),
                (14, 'Soacha'),
                (14, 'Sopó'),
                (14, 'Subachoque'),
                (14, 'Suesca'),
                (14, 'Supatá'),
                (14, 'Susa'),
                (14, 'Sutatausa'),
                (14, 'Tabio'),
                (14, 'Tausa'),
                (14, 'Tena'),
                (14, 'Tenjo'),
                (14, 'Tibacuy'),
                (14, 'Tibirita'),
                (14, 'Tocaima'),
                (14, 'Tocancipá'),
                (14, 'Topaipí'),
                (14, 'Ubalá'),
                (14, 'Ubaque'),
                (14, 'Villa de San Diego de Ubate'),
                (14, 'Une'),
                (14, 'Útica'),
                (14, 'Vergara'),
                (14, 'Vianí'),
                (14, 'Villagómez'),
                (14, 'Villapinzón'),
                (14, 'Villeta'),
                (14, 'Viotá'),
                (14, 'Yacopí'),
                (14, 'Zipacón'),
                (12, 'Acandí'),
                (12, 'Alto Baudo'),
                (12, 'Atrato'),
                (12, 'Bagadó'),
                (12, 'Bahía Solano'),
                (12, 'Bajo Baudó'),
                (12, 'Belén de Bajira'),
                (12, 'Bojaya'),
                (12, 'El Cantón del San Pablo'),
                (12, 'Carmen del Darien'),
                (12, 'Cértegui'),
                (12, 'Condoto'),
                (12, 'El Carmen de Atrato'),
                (12, 'El Litoral del San Juan'),
                (12, 'Istmina'),
                (12, 'Juradó'),
                (12, 'Lloró'),
                (12, 'Medio Atrato'),
                (12, 'Medio Baudó'),
                (12, 'Medio San Juan'),
                (12, 'Nóvita'),
                (12, 'Nuquí'),
                (12, 'Río Iro'),
                (12, 'Río Quito'),
                (12, 'Riosucio'),
                (12, 'San José del Palmar'),
                (12, 'Sipí'),
                (12, 'Tadó'),
                (12, 'Unguía'),
                (12, 'Unión Panamericana'),
                (17, 'Acevedo'),
                (17, 'Agrado'),
                (17, 'Aipe'),
                (17, 'Algeciras'),
                (17, 'Altamira'),
                (17, 'Baraya'),
                (17, 'Campoalegre'),
                (17, 'Colombia'),
                (17, 'Elías'),
                (17, 'Garzón'),
                (17, 'Gigante'),
                (17, 'Guadalupe'),
                (17, 'Hobo'),
                (17, 'Iquira'),
                (17, 'Isnos'),
                (17, 'La Argentina'),
                (17, 'La Plata'),
                (17, 'Nátaga'),
                (17, 'Oporapa'),
                (17, 'Paicol'),
                (17, 'Palermo'),
                (17, 'Palestina'),
                (17, 'Pital'),
                (17, 'Pitalito'),
                (17, 'Rivera'),
                (17, 'Saladoblanco'),
                (17, 'San Agustín'),
                (17, 'Santa María'),
                (17, 'Suaza'),
                (17, 'Tarqui'),
                (17, 'Tesalia'),
                (17, 'Tello'),
                (17, 'Teruel'),
                (17, 'Timaná'),
                (17, 'Villavieja'),
                (17, 'Yaguará'),
                (18, 'Albania'),
                (18, 'Barrancas'),
                (18, 'Dibula'),
                (18, 'Distracción'),
                (18, 'El Molino'),
                (18, 'Fonseca'),
                (18, 'Hatonuevo'),
                (18, 'La Jagua del Pilar'),
                (18, 'Maicao'),
                (18, 'Manaure'),
                (18, 'San Juan del Cesar'),
                (18, 'Uribia'),
                (18, 'Urumita'),
                (18, 'Villanueva'),
                (19, 'Algarrobo'),
                (19, 'Aracataca'),
                (19, 'Ariguaní'),
                (19, 'Cerro San Antonio'),
                (19, 'Chivolo'),
                (19, 'Ciénaga'),
                (19, 'Concordia'),
                (19, 'El Banco'),
                (19, 'El Piñon'),
                (19, 'El Retén'),
                (19, 'Fundación'),
                (19, 'Guamal'),
                (19, 'Nueva Granada'),
                (19, 'Pedraza'),
                (19, 'Pijiño del Carmen'),
                (19, 'Pivijay'),
                (19, 'Plato'),
                (19, 'Pueblo Viejo'),
                (19, 'Remolino'),
                (19, 'Sabanas de San Angel'),
                (19, 'Salamina'),
                (19, 'San Sebastián de Buenavista'),
                (19, 'San Zenón'),
                (19, 'Santa Ana'),
                (19, 'Santa Bárbara de Pinto'),
                (19, 'Sitionuevo'),
                (19, 'Tenerife'),
                (19, 'Zapayán'),
                (19, 'Zona Bananera'),
                (20, 'Acacias'),
                (20, 'Barranca de Upía'),
                (20, 'Cabuyaro'),
                (20, 'Castilla la Nueva'),
                (20, 'Cubarral'),
                (20, 'Cumaral'),
                (20, 'El Calvario'),
                (20, 'El Castillo'),
                (20, 'El Dorado'),
                (20, 'Fuente de Oro'),
                (20, 'Granada'),
                (20, 'Guamal'),
                (20, 'Mapiripán'),
                (20, 'Mesetas'),
                (20, 'La Macarena'),
                (20, 'Uribe'),
                (20, 'Lejanías'),
                (20, 'Puerto Concordia'),
                (20, 'Puerto Gaitán'),
                (20, 'Puerto López'),
                (20, 'Puerto Lleras'),
                (20, 'Puerto Rico'),
                (20, 'Restrepo'),
                (20, 'San Carlos de Guaroa'),
                (20, 'San Juan de Arama'),
                (20, 'San Juanito'),
                (20, 'San Martín'),
                (20, 'Vista Hermosa'),
                (21, 'Albán'),
                (21, 'Aldana'),
                (21, 'Ancuyá'),
                (21, 'Arboleda'),
                (21, 'Barbacoas'),
                (21, 'Belén'),
                (21, 'Buesaco'),
                (21, 'Colón'),
                (21, 'Consaca'),
                (21, 'Contadero'),
                (21, 'Córdoba'),
                (21, 'Cuaspud'),
                (21, 'Cumbal'),
                (21, 'Cumbitara'),
                (21, 'Chachagüí'),
                (21, 'El Charco'),
                (21, 'El Peñol'),
                (21, 'El Rosario'),
                (21, 'El Tablón de Gómez'),
                (21, 'El Tambo'),
                (21, 'Funes'),
                (21, 'Guachucal'),
                (21, 'Guaitarilla'),
                (21, 'Gualmatán'),
                (21, 'Iles'),
                (21, 'Imués'),
                (21, 'Ipiales'),
                (21, 'La Cruz'),
                (21, 'La Florida'),
                (21, 'La Llanada'),
                (21, 'La Tola'),
                (21, 'La Unión'),
                (21, 'Leiva'),
                (21, 'Linares'),
                (21, 'Los Andes'),
                (21, 'Magüí'),
                (21, 'Mallama'),
                (21, 'Mosquera'),
                (21, 'Nariño'),
                (21, 'Olaya Herrera'),
                (21, 'Ospina'),
                (21, 'Francisco Pizarro'),
                (21, 'Policarpa'),
                (21, 'Potosí'),
                (21, 'Providencia'),
                (21, 'Puerres'),
                (21, 'Pupiales'),
                (21, 'Ricaurte'),
                (21, 'Roberto Payán'),
                (21, 'Samaniego'),
                (21, 'Sandoná'),
                (21, 'San Bernardo'),
                (21, 'San Lorenzo'),
                (21, 'San Pablo'),
                (21, 'San Pedro de Cartago'),
                (21, 'Santa Bárbara'),
                (21, 'Santacruz'),
                (21, 'Sapuyes'),
                (21, 'Taminango'),
                (21, 'Tangua'),
                (21, 'San Andrés de Tumaco'),
                (21, 'Túquerres'),
                (21, 'Yacuanquer'),
                (22, 'Abrego'),
                (22, 'Arboledas'),
                (22, 'Bochalema'),
                (22, 'Bucarasica'),
                (22, 'Cácota'),
                (22, 'Cachirá'),
                (22, 'Chinácota'),
                (22, 'Chitagá'),
                (22, 'Convención'),
                (22, 'Cucutilla'),
                (22, 'Durania'),
                (22, 'El Carmen'),
                (22, 'El Tarra'),
                (22, 'El Zulia'),
                (22, 'Gramalote'),
                (22, 'Hacarí'),
                (22, 'Herrán'),
                (22, 'Labateca'),
                (22, 'La Esperanza'),
                (22, 'La Playa'),
                (22, 'Los Patios'),
                (22, 'Lourdes'),
                (22, 'Mutiscua'),
                (22, 'Ocaña'),
                (22, 'Pamplona'),
                (22, 'Pamplonita'),
                (22, 'Puerto Santander'),
                (22, 'Ragonvalia'),
                (22, 'Salazar'),
                (22, 'San Calixto'),
                (22, 'San Cayetano'),
                (22, 'Santiago'),
                (22, 'Sardinata'),
                (22, 'Silos'),
                (22, 'Teorama'),
                (22, 'Tibú'),
                (22, 'Toledo'),
                (22, 'Villa Caro'),
                (22, 'Villa del Rosario'),
                (24, 'Buenavista'),
                (24, 'Calarcá'),
                (24, 'Circasia'),
                (24, 'Córdoba'),
                (24, 'Filandia'),
                (24, 'Génova'),
                (24, 'La Tebaida'),
                (24, 'Montenegro'),
                (24, 'Pijao'),
                (24, 'Quimbaya'),
                (24, 'Salento'),
                (25, 'Apía'),
                (25, 'Balboa'),
                (25, 'Belén de Umbría'),
                (25, 'Dosquebradas'),
                (25, 'Guática'),
                (25, 'La Celia'),
                (25, 'La Virginia'),
                (25, 'Marsella'),
                (25, 'Mistrató'),
                (25, 'Pueblo Rico'),
                (25, 'Quinchía'),
                (25, 'Santa Rosa de Cabal'),
                (25, 'Santuario'),
                (27, 'Aguada'),
                (27, 'Albania'),
                (27, 'Aratoca'),
                (27, 'Barbosa'),
                (27, 'Barichara'),
                (27, 'Barrancabermeja'),
                (27, 'Betulia'),
                (27, 'Bolívar'),
                (27, 'Cabrera'),
                (27, 'California'),
                (27, 'Capitanejo'),
                (27, 'Carcasí'),
                (27, 'Cepitá'),
                (27, 'Cerrito'),
                (27, 'Charalá'),
                (27, 'Charta'),
                (27, 'Chimá'),
                (27, 'Chipatá'),
                (27, 'Cimitarra'),
                (27, 'Concepción'),
                (27, 'Confines'),
                (27, 'Contratación'),
                (27, 'Coromoro'),
                (27, 'Curití'),
                (27, 'El Carmen de Chucurí'),
                (27, 'El Guacamayo'),
                (27, 'El Peñón'),
                (27, 'El Playón'),
                (27, 'Encino'),
                (27, 'Enciso'),
                (27, 'Florián'),
                (27, 'Floridablanca'),
                (27, 'Galán'),
                (27, 'Gambita'),
                (27, 'Girón'),
                (27, 'Guaca'),
                (27, 'Guadalupe'),
                (27, 'Guapotá'),
                (27, 'Guavatá'),
                (27, 'Güepsa'),
                (27, 'Hato'),
                (27, 'Jesús María'),
                (27, 'Jordán'),
                (27, 'La Belleza'),
                (27, 'Landázuri'),
                (27, 'La Paz'),
                (27, 'Lebríja'),
                (27, 'Los Santos'),
                (27, 'Macaravita'),
                (27, 'Málaga'),
                (27, 'Matanza'),
                (27, 'Mogotes'),
                (27, 'Molagavita'),
                (27, 'Ocamonte'),
                (27, 'Oiba'),
                (27, 'Onzaga'),
                (27, 'Palmar'),
                (27, 'Palmas del Socorro'),
                (27, 'Páramo'),
                (27, 'Piedecuesta'),
                (27, 'Pinchote'),
                (27, 'Puente Nacional'),
                (27, 'Puerto Parra'),
                (27, 'Puerto Wilches'),
                (27, 'Rionegro'),
                (27, 'Sabana de Torres'),
                (27, 'San Andrés'),
                (27, 'San Benito'),
                (27, 'San Gil'),
                (27, 'San Joaquín'),
                (27, 'San José de Miranda'),
                (27, 'San Miguel'),
                (27, 'San Vicente de Chucurí'),
                (27, 'Santa Bárbara'),
                (27, 'Santa Helena del Opón'),
                (27, 'Simacota'),
                (27, 'Socorro'),
                (27, 'Suaita'),
                (27, 'Sucre'),
                (27, 'Suratá'),
                (27, 'Tona'),
                (27, 'Valle de San José'),
                (27, 'Vélez'),
                (27, 'Vetas'),
                (27, 'Villanueva'),
                (27, 'Zapatoca'),
                (28, 'Buenavista'),
                (28, 'Caimito'),
                (28, 'Coloso'),
                (28, 'Corozal'),
                (28, 'Coveñas'),
                (28, 'Chalán'),
                (28, 'El Roble'),
                (28, 'Galeras'),
                (28, 'Guaranda'),
                (28, 'La Unión');
            ");

            migrationBuilder.Sql(@"
                INSERT INTO Municipios (DepartamentoId, Nombre) VALUES
                (28, 'Los Palmitos'),
                (28, 'Majagual'),
                (28, 'Morroa'),
                (28, 'Ovejas'),
                (28, 'Palmito'),
                (28, 'Sampués'),
                (28, 'San Benito Abad'),
                (28, 'San Juan de Betulia'),
                (28, 'San Marcos'),
                (28, 'San Onofre'),
                (28, 'San Pedro'),
                (28, 'San Luis de Sincé'),
                (28, 'Sucre'),
                (28, 'Santiago de Tolú'),
                (28, 'Tolú Viejo'),
                (29, 'Alpujarra'),
                (29, 'Alvarado'),
                (29, 'Ambalema'),
                (29, 'Anzoátegui'),
                (29, 'Armero'),
                (29, 'Ataco'),
                (29, 'Cajamarca'),
                (29, 'Carmen de Apicala'),
                (29, 'Casabianca'),
                (29, 'Chaparral'),
                (29, 'Coello'),
                (29, 'Coyaima'),
                (29, 'Cunday'),
                (29, 'Dolores'),
                (29, 'Espinal'),
                (29, 'Falan'),
                (29, 'Flandes'),
                (29, 'Fresno'),
                (29, 'Guamo'),
                (29, 'Herveo'),
                (29, 'Honda'),
                (29, 'Icononzo'),
                (29, 'Lérida'),
                (29, 'Líbano'),
                (29, 'Mariquita'),
                (29, 'Melgar'),
                (29, 'Murillo'),
                (29, 'Natagaima'),
                (29, 'Ortega'),
                (29, 'Palocabildo'),
                (29, 'Piedras'),
                (29, 'Planadas'),
                (29, 'Prado'),
                (29, 'Purificación'),
                (29, 'Rio Blanco'),
                (29, 'Roncesvalles'),
                (29, 'Rovira'),
                (29, 'Saldaña'),
                (29, 'San Antonio'),
                (29, 'San Luis'),
                (29, 'Santa Isabel'),
                (29, 'Suárez'),
                (29, 'Valle de San Juan'),
                (29, 'Venadillo'),
                (29, 'Villahermosa'),
                (29, 'Villarrica'),
                (30, 'Alcalá'),
                (30, 'Andalucía'),
                (30, 'Ansermanuevo'),
                (30, 'Argelia'),
                (30, 'Bolívar'),
                (30, 'Buenaventura'),
                (30, 'Guadalajara de Buga'),
                (30, 'Bugalagrande'),
                (30, 'Caicedonia'),
                (30, 'Calima'),
                (30, 'Candelaria'),
                (30, 'Cartago'),
                (30, 'Dagua'),
                (30, 'El Águila'),
                (30, 'El Cairo'),
                (30, 'El Cerrito'),
                (30, 'El Dovio'),
                (30, 'Florida'),
                (30, 'Ginebra'),
                (30, 'Guacarí'),
                (30, 'Jamundí'),
                (30, 'La Cumbre'),
                (30, 'La Unión'),
                (30, 'La Victoria'),
                (30, 'Obando'),
                (30, 'Palmira'),
                (30, 'Pradera'),
                (30, 'Restrepo'),
                (30, 'Riofrío'),
                (30, 'Roldanillo'),
                (30, 'San Pedro'),
                (30, 'Sevilla'),
                (30, 'Toro'),
                (30, 'Trujillo'),
                (30, 'Tuluá'),
                (30, 'Ulloa'),
                (30, 'Versalles'),
                (30, 'Vijes'),
                (30, 'Yotoco'),
                (30, 'Yumbo'),
                (30, 'Zarzal'),
                (3, 'Arauquita'),
                (3, 'Cravo Norte'),
                (3, 'Fortul'),
                (3, 'Puerto Rondón'),
                (3, 'Saravena'),
                (3, 'Tame'),
                (9, 'Aguazul'),
                (9, 'Chámeza'),
                (9, 'Hato Corozal'),
                (9, 'La Salina'),
                (9, 'Maní'),
                (9, 'Monterrey'),
                (9, 'Nunchía'),
                (9, 'Orocué'),
                (9, 'Paz de Ariporo'),
                (9, 'Pore'),
                (9, 'Recetor'),
                (9, 'Sabanalarga'),
                (9, 'Sácama'),
                (9, 'San Luis de Gaceno'),
                (9, 'Támara'),
                (9, 'Tauramena'),
                (9, 'Trinidad'),
                (9, 'Villanueva'),
                (23, 'Colón'),
                (23, 'Orito'),
                (23, 'Puerto Asís'),
                (23, 'Puerto Caicedo'),
                (23, 'Puerto Guzmán'),
                (23, 'Leguízamo'),
                (23, 'Sibundoy'),
                (23, 'San Francisco'),
                (23, 'San Miguel'),
                (23, 'Santiago'),
                (23, 'Valle de Guamez'),
                (23, 'Villagarzón'),
                (26, 'Providencia'),
                (1, 'El Encanto'),
                (1, 'La Chorrera'),
                (1, 'La Pedrera'),
                (1, 'La Victoria'),
                (1, 'Miriti Paraná'),
                (1, 'Puerto Alegría'),
                (1, 'Puerto Arica'),
                (1, 'Puerto Nariño'),
                (1, 'Puerto Santander'),
                (1, 'Tarapacá'),
                (15, 'Barranco Minas'),
                (15, 'Mapiripana'),
                (15, 'San Felipe'),
                (15, 'Puerto Colombia'),
                (15, 'La Guadalupe'),
                (15, 'Cacahual'),
                (15, 'Pana Pana'),
                (15, 'Morichal'),
                (16, 'Calamar'),
                (16, 'El Retorno'),
                (16, 'Miraflores'),
                (31, 'Caruru'),
                (31, 'Pacoa'),
                (31, 'Taraira'),
                (31, 'Papunaua'),
                (31, 'Yavaraté'),
                (32, 'La Primavera'),
                (32, 'Santa Rosalía'),
                (32, 'Cumaribo');
            ");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DELETE m FROM Municipios m
                INNER JOIN (VALUES
                    (2, 'Abejorral'),
                    (2, 'Abriaquí'),
                    (2, 'Alejandría'),
                    (2, 'Amagá'),
                    (2, 'Amalfi'),
                    (2, 'Andes'),
                    (2, 'Angelópolis'),
                    (2, 'Angostura'),
                    (2, 'Anorí'),
                    (2, 'Santafé de Antioquia'),
                    (2, 'Anza'),
                    (2, 'Apartadó'),
                    (2, 'Arboletes'),
                    (2, 'Argelia'),
                    (2, 'Armenia'),
                    (2, 'Barbosa'),
                    (2, 'Belmira'),
                    (2, 'Bello'),
                    (2, 'Betania'),
                    (2, 'Betulia'),
                    (2, 'Ciudad Bolívar'),
                    (2, 'Briceño'),
                    (2, 'Buriticá'),
                    (2, 'Cáceres'),
                    (2, 'Caicedo'),
                    (2, 'Caldas'),
                    (2, 'Campamento'),
                    (2, 'Cañasgordas'),
                    (2, 'Caracolí'),
                    (2, 'Caramanta'),
                    (2, 'Carepa'),
                    (2, 'El Carmen de Viboral'),
                    (2, 'Carolina'),
                    (2, 'Caucasia'),
                    (2, 'Chigorodó'),
                    (2, 'Cisneros'),
                    (2, 'Cocorná'),
                    (2, 'Concepción'),
                    (2, 'Concordia'),
                    (2, 'Copacabana'),
                    (2, 'Dabeiba'),
                    (2, 'Don Matías'),
                    (2, 'Ebéjico'),
                    (2, 'El Bagre'),
                    (2, 'Entrerrios'),
                    (2, 'Envigado'),
                    (2, 'Fredonia'),
                    (2, 'Frontino'),
                    (2, 'Giraldo'),
                    (2, 'Girardota'),
                    (2, 'Gómez Plata'),
                    (2, 'Granada'),
                    (2, 'Guadalupe'),
                    (2, 'Guarne'),
                    (2, 'Guatapé'),
                    (2, 'Heliconia'),
                    (2, 'Hispania'),
                    (2, 'Itagui'),
                    (2, 'Ituango'),
                    (2, 'Jardín'),
                    (2, 'Jericó'),
                    (2, 'La Ceja'),
                    (2, 'La Estrella'),
                    (2, 'La Pintada'),
                    (2, 'La Unión'),
                    (2, 'Liborina'),
                    (2, 'Maceo'),
                    (2, 'Marinilla'),
                    (2, 'Montebello'),
                    (2, 'Murindó'),
                    (2, 'Mutatá'),
                    (2, 'Nariño'),
                    (2, 'Necoclí'),
                    (2, 'Nechí'),
                    (2, 'Olaya'),
                    (2, 'Peñol'),
                    (2, 'Peque'),
                    (2, 'Pueblorrico'),
                    (2, 'Puerto Berrío'),
                    (2, 'Puerto Nare'),
                    (2, 'Puerto Triunfo'),
                    (2, 'Remedios'),
                    (2, 'Retiro'),
                    (2, 'Rionegro'),
                    (2, 'Sabanalarga'),
                    (2, 'Sabaneta'),
                    (2, 'Salgar'),
                    (2, 'San Andrés de Cuerquía'),
                    (2, 'San Carlos'),
                    (2, 'San Francisco'),
                    (2, 'San Jerónimo'),
                    (2, 'San José de La Montaña'),
                    (2, 'San Juan de Urabá'),
                    (2, 'San Luis'),
                    (2, 'San Pedro'),
                    (2, 'San Pedro de Uraba'),
                    (2, 'San Rafael'),
                    (2, 'San Roque'),
                    (2, 'San Vicente'),
                    (2, 'Santa Bárbara'),
                    (2, 'Santa Rosa de Osos'),
                    (2, 'Santo Domingo'),
                    (2, 'El Santuario'),
                    (2, 'Segovia'),
                    (2, 'Sonsón'),
                    (2, 'Sopetrán'),
                    (2, 'Támesis'),
                    (2, 'Tarazá'),
                    (2, 'Tarso'),
                    (2, 'Titiribí'),
                    (2, 'Toledo'),
                    (2, 'Turbo'),
                    (2, 'Uramita'),
                    (2, 'Urrao'),
                    (2, 'Valdivia'),
                    (2, 'Valparaíso'),
                    (2, 'Vegachí'),
                    (2, 'Venecia'),
                    (2, 'Vigía del Fuerte'),
                    (2, 'Yalí'),
                    (2, 'Yarumal'),
                    (2, 'Yolombó'),
                    (2, 'Yondó'),
                    (2, 'Zaragoza'),
                    (4, 'Baranoa'),
                    (4, 'Campo de La Cruz'),
                    (4, 'Candelaria'),
                    (4, 'Galapa'),
                    (4, 'Juan de Acosta'),
                    (4, 'Luruaco'),
                    (4, 'Malambo'),
                    (4, 'Manatí'),
                    (4, 'Palmar de Varela'),
                    (4, 'Piojó'),
                    (4, 'Polonuevo'),
                    (4, 'Ponedera'),
                    (4, 'Puerto Colombia'),
                    (4, 'Repelón'),
                    (4, 'Sabanagrande'),
                    (4, 'Sabanalarga'),
                    (4, 'Santa Lucía'),
                    (4, 'Santo Tomás'),
                    (4, 'Soledad'),
                    (4, 'Suan'),
                    (4, 'Tubará'),
                    (4, 'Usiacurí'),
                    (5, 'Cartagena'),
                    (5, 'Achí'),
                    (5, 'Altos del Rosario'),
                    (5, 'Arenal'),
                    (5, 'Arjona'),
                    (5, 'Arroyohondo'),
                    (5, 'Barranco de Loba'),
                    (5, 'Calamar'),
                    (5, 'Cantagallo'),
                    (5, 'Cicuco'),
                    (5, 'Córdoba'),
                    (5, 'Clemencia'),
                    (5, 'El Carmen de Bolívar'),
                    (5, 'El Guamo'),
                    (5, 'El Peñón'),
                    (5, 'Hatillo de Loba'),
                    (5, 'Magangué'),
                    (5, 'Mahates'),
                    (5, 'Margarita'),
                    (5, 'María la Baja'),
                    (5, 'Montecristo'),
                    (5, 'Mompós'),
                    (5, 'Morales'),
                    (5, 'Norosí'),
                    (5, 'Pinillos'),
                    (5, 'Regidor'),
                    (5, 'Río Viejo'),
                    (5, 'San Cristóbal'),
                    (5, 'San Estanislao'),
                    (5, 'San Fernando'),
                    (5, 'San Jacinto'),
                    (5, 'San Jacinto del Cauca'),
                    (5, 'San Juan Nepomuceno'),
                    (5, 'San Martín de Loba'),
                    (5, 'San Pablo de Borbur'),
                    (5, 'Santa Catalina'),
                    (5, 'Santa Rosa'),
                    (5, 'Santa Rosa del Sur'),
                    (5, 'Simití'),
                    (5, 'Soplaviento'),
                    (5, 'Talaigua Nuevo'),
                    (5, 'Tiquisio'),
                    (5, 'Turbaco'),
                    (5, 'Turbaná'),
                    (5, 'Villanueva'),
                    (5, 'Zambrano'),
                    (6, 'Almeida'),
                    (6, 'Aquitania'),
                    (6, 'Arcabuco'),
                    (6, 'Belén'),
                    (6, 'Berbeo'),
                    (6, 'Betéitiva'),
                    (6, 'Boavita'),
                    (6, 'Boyacá'),
                    (6, 'Briceño'),
                    (6, 'Buena Vista'),
                    (6, 'Busbanzá'),
                    (6, 'Caldas'),
                    (6, 'Campohermoso'),
                    (6, 'Cerinza'),
                    (6, 'Chinavita'),
                    (6, 'Chiquinquirá'),
                    (6, 'Chiscas'),
                    (6, 'Chita'),
                    (6, 'Chitaraque'),
                    (6, 'Chivatá'),
                    (6, 'Ciénega'),
                    (6, 'Cómbita'),
                    (6, 'Coper'),
                    (6, 'Corrales'),
                    (6, 'Covarachía'),
                    (6, 'Cubará'),
                    (6, 'Cucaita'),
                    (6, 'Cuítiva'),
                    (6, 'Chíquiza'),
                    (6, 'Chivor'),
                    (6, 'Duitama'),
                    (6, 'El Cocuy'),
                    (6, 'El Espino'),
                    (6, 'Firavitoba'),
                    (6, 'Floresta'),
                    (6, 'Gachantivá'),
                    (6, 'Gameza'),
                    (6, 'Garagoa'),
                    (6, 'Guacamayas'),
                    (6, 'Guateque'),
                    (6, 'Guayatá'),
                    (6, 'Güicán'),
                    (6, 'Iza'),
                    (6, 'Jenesano'),
                    (6, 'Jericó'),
                    (6, 'Labranzagrande'),
                    (6, 'La Capilla'),
                    (6, 'La Victoria'),
                    (6, 'La Uvita'),
                    (6, 'Villa de Leyva'),
                    (6, 'Macanal'),
                    (6, 'Maripí'),
                    (6, 'Miraflores'),
                    (6, 'Mongua'),
                    (6, 'Monguí'),
                    (6, 'Moniquirá'),
                    (6, 'Motavita'),
                    (6, 'Muzo'),
                    (6, 'Nobsa'),
                    (6, 'Nuevo Colón'),
                    (6, 'Oicatá'),
                    (6, 'Otanche'),
                    (6, 'Pachavita'),
                    (6, 'Páez'),
                    (6, 'Paipa'),
                    (6, 'Pajarito'),
                    (6, 'Panqueba'),
                    (6, 'Pauna'),
                    (6, 'Paya'),
                    (6, 'Paz de Río'),
                    (6, 'Pesca'),
                    (6, 'Pisba'),
                    (6, 'Puerto Boyacá'),
                    (6, 'Quípama'),
                    (6, 'Ramiriquí'),
                    (6, 'Ráquira'),
                    (6, 'Rondón'),
                    (6, 'Saboyá'),
                    (6, 'Sáchica'),
                    (6, 'Samacá'),
                    (6, 'San Eduardo'),
                    (6, 'San José de Pare'),
                    (6, 'San Luis de Gaceno'),
                    (6, 'San Mateo'),
                    (6, 'San Miguel de Sema'),
                    (6, 'San Pablo de Borbur'),
                    (6, 'Santana'),
                    (6, 'Santa María'),
                    (6, 'Santa Rosa de Viterbo'),
                    (6, 'Santa Sofía'),
                    (6, 'Sativanorte'),
                    (6, 'Sativasur'),
                    (6, 'Siachoque'),
                    (6, 'Soatá'),
                    (6, 'Socotá'),
                    (6, 'Socha'),
                    (6, 'Sogamoso'),
                    (6, 'Somondoco'),
                    (6, 'Sora'),
                    (6, 'Sotaquirá'),
                    (6, 'Soracá'),
                    (6, 'Susacón'),
                    (6, 'Sutamarchán'),
                    (6, 'Sutatenza'),
                    (6, 'Tasco'),
                    (6, 'Tenza'),
                    (6, 'Tibaná'),
                    (6, 'Tibasosa'),
                    (6, 'Tinjacá'),
                    (6, 'Tipacoque'),
                    (6, 'Toca'),
                    (6, 'Togüí'),
                    (6, 'Tópaga'),
                    (6, 'Tota'),
                    (6, 'Tununguá'),
                    (6, 'Turmequé'),
                    (6, 'Tuta'),
                    (6, 'Tutazá'),
                    (6, 'Umbita'),
                    (6, 'Ventaquemada'),
                    (6, 'Viracachá'),
                    (6, 'Zetaquira'),
                    (7, 'Aguadas'),
                    (7, 'Anserma'),
                    (7, 'Aranzazu'),
                    (7, 'Belalcázar'),
                    (7, 'Chinchiná'),
                    (7, 'Filadelfia'),
                    (7, 'La Dorada'),
                    (7, 'La Merced'),
                    (7, 'Manzanares'),
                    (7, 'Marmato'),
                    (7, 'Marquetalia'),
                    (7, 'Marulanda'),
                    (7, 'Neira'),
                    (7, 'Norcasia'),
                    (7, 'Pácora'),
                    (7, 'Palestina'),
                    (7, 'Pensilvania'),
                    (7, 'Riosucio'),
                    (7, 'Risaralda'),
                    (7, 'Salamina'),
                    (7, 'Samaná'),
                    (7, 'San José'),
                    (7, 'Supía'),
                    (7, 'Victoria'),
                    (7, 'Villamaría'),
                    (7, 'Viterbo'),
                    (8, 'Albania'),
                    (8, 'Belén de Los Andaquies'),
                    (8, 'Cartagena del Chairá'),
                    (8, 'Curillo'),
                    (8, 'El Doncello'),
                    (8, 'El Paujil'),
                    (8, 'La Montañita'),
                    (8, 'Milán'),
                    (8, 'Morelia'),
                    (8, 'Puerto Rico'),
                    (8, 'San José del Fragua'),
                    (8, 'San Vicente del Caguán'),
                    (8, 'Solano'),
                    (8, 'Solita'),
                    (8, 'Valparaíso'),
                    (10, 'Almaguer'),
                    (10, 'Argelia'),
                    (10, 'Balboa'),
                    (10, 'Bolívar'),
                    (10, 'Buenos Aires'),
                    (10, 'Cajibío'),
                    (10, 'Caldono'),
                    (10, 'Caloto'),
                    (10, 'Corinto'),
                    (10, 'El Tambo'),
                    (10, 'Florencia'),
                    (10, 'Guachené'),
                    (10, 'Guapi'),
                    (10, 'Inzá'),
                    (10, 'Jambaló'),
                    (10, 'La Sierra'),
                    (10, 'La Vega'),
                    (10, 'López'),
                    (10, 'Mercaderes'),
                    (10, 'Miranda'),
                    (10, 'Morales'),
                    (10, 'Padilla'),
                    (10, 'Páez'),
                    (10, 'Patía'),
                    (10, 'Piamonte'),
                    (10, 'Piendamó'),
                    (10, 'Puerto Tejada'),
                    (10, 'Puracé'),
                    (10, 'Rosas'),
                    (10, 'San Sebastián'),
                    (10, 'Santander de Quilichao'),
                    (10, 'Santa Rosa'),
                    (10, 'Silvia'),
                    (10, 'Sotara'),
                    (10, 'Suárez'),
                    (10, 'Sucre'),
                    (10, 'Timbío'),
                    (10, 'Timbiquí'),
                    (10, 'Toribio'),
                    (10, 'Totoró'),
                    (10, 'Villa Rica'),
                    (11, 'Manaure'),
                    (13, 'Ayapel'),
                    (13, 'Buenavista'),
                    (13, 'Canalete'),
                    (13, 'Cereté'),
                    (13, 'Chimá'),
                    (13, 'Chinú'),
                    (13, 'Ciénaga de Oro'),
                    (13, 'Cotorra'),
                    (13, 'La Apartada'),
                    (13, 'Lorica'),
                    (13, 'Los Córdobas'),
                    (13, 'Momil'),
                    (13, 'Montelíbano'),
                    (13, 'Moñitos'),
                    (13, 'Planeta Rica'),
                    (13, 'Pueblo Nuevo'),
                    (13, 'Puerto Escondido'),
                    (13, 'Puerto Libertador'),
                    (13, 'Purísima'),
                    (13, 'Sahagún'),
                    (13, 'San Andrés Sotavento'),
                    (13, 'San Antero'),
                    (13, 'San Bernardo del Viento'),
                    (13, 'San Carlos'),
                    (13, 'San José de Uré'),
                    (13, 'San Pelayo'),
                    (13, 'Tierralta'),
                    (13, 'Tuchín'),
                    (13, 'Valencia'),
                    (14, 'Agua de Dios'),
                    (14, 'Albán'),
                    (14, 'Anapoima'),
                    (14, 'Anolaima'),
                    (14, 'Arbeláez'),
                    (14, 'Beltrán'),
                    (14, 'Bituima'),
                    (14, 'Bojacá'),
                    (14, 'Cabrera'),
                    (14, 'Cachipay'),
                    (14, 'Cajicá'),
                    (14, 'Caparrapí'),
                    (14, 'Caqueza'),
                    (14, 'Carmen de Carupa'),
                    (14, 'Chaguaní'),
                    (14, 'Chía'),
                    (14, 'Chipaque'),
                    (14, 'Choachí'),
                    (14, 'Chocontá'),
                    (14, 'Cogua'),
                    (14, 'Cota'),
                    (14, 'Cucunubá'),
                    (14, 'El Colegio'),
                    (14, 'El Peñón'),
                    (14, 'El Rosal'),
                    (14, 'Facatativá'),
                    (14, 'Fomeque'),
                    (14, 'Fosca'),
                    (14, 'Funza'),
                    (14, 'Fúquene'),
                    (14, 'Fusagasugá'),
                    (14, 'Gachala'),
                    (14, 'Gachancipá'),
                    (14, 'Gachetá'),
                    (14, 'Gama'),
                    (14, 'Girardot'),
                    (14, 'Granada'),
                    (14, 'Guachetá'),
                    (14, 'Guaduas'),
                    (14, 'Guasca'),
                    (14, 'Guataquí'),
                    (14, 'Guatavita'),
                    (14, 'Guayabal de Siquima'),
                    (14, 'Guayabetal'),
                    (14, 'Gutiérrez'),
                    (14, 'Jerusalén'),
                    (14, 'Junín'),
                    (14, 'La Calera'),
                    (14, 'La Mesa'),
                    (14, 'La Palma'),
                    (14, 'La Peña'),
                    (14, 'La Vega'),
                    (14, 'Lenguazaque'),
                    (14, 'Macheta'),
                    (14, 'Madrid'),
                    (14, 'Manta'),
                    (14, 'Medina'),
                    (14, 'Mosquera'),
                    (14, 'Nariño'),
                    (14, 'Nemocón'),
                    (14, 'Nilo'),
                    (14, 'Nimaima'),
                    (14, 'Nocaima'),
                    (14, 'Venecia'),
                    (14, 'Pacho'),
                    (14, 'Paime'),
                    (14, 'Pandi'),
                    (14, 'Paratebueno'),
                    (14, 'Pasca'),
                    (14, 'Puerto Salgar'),
                    (14, 'Pulí'),
                    (14, 'Quebradanegra'),
                    (14, 'Quetame'),
                    (14, 'Quipile'),
                    (14, 'Apulo'),
                    (14, 'Ricaurte'),
                    (14, 'San Antonio del Tequendama'),
                    (14, 'San Bernardo'),
                    (14, 'San Cayetano'),
                    (14, 'San Francisco'),
                    (14, 'San Juan de Río Seco'),
                    (14, 'Sasaima'),
                    (14, 'Sesquilé'),
                    (14, 'Sibaté'),
                    (14, 'Silvania'),
                    (14, 'Simijaca'),
                    (14, 'Soacha'),
                    (14, 'Sopó'),
                    (14, 'Subachoque'),
                    (14, 'Suesca'),
                    (14, 'Supatá'),
                    (14, 'Susa'),
                    (14, 'Sutatausa'),
                    (14, 'Tabio'),
                    (14, 'Tausa'),
                    (14, 'Tena'),
                    (14, 'Tenjo'),
                    (14, 'Tibacuy'),
                    (14, 'Tibirita'),
                    (14, 'Tocaima'),
                    (14, 'Tocancipá'),
                    (14, 'Topaipí'),
                    (14, 'Ubalá'),
                    (14, 'Ubaque'),
                    (14, 'Villa de San Diego de Ubate'),
                    (14, 'Une'),
                    (14, 'Útica'),
                    (14, 'Vergara'),
                    (14, 'Vianí'),
                    (14, 'Villagómez'),
                    (14, 'Villapinzón'),
                    (14, 'Villeta'),
                    (14, 'Viotá'),
                    (14, 'Yacopí'),
                    (14, 'Zipacón'),
                    (12, 'Acandí'),
                    (12, 'Alto Baudo'),
                    (12, 'Atrato'),
                    (12, 'Bagadó'),
                    (12, 'Bahía Solano'),
                    (12, 'Bajo Baudó'),
                    (12, 'Belén de Bajira'),
                    (12, 'Bojaya'),
                    (12, 'El Cantón del San Pablo'),
                    (12, 'Carmen del Darien'),
                    (12, 'Cértegui'),
                    (12, 'Condoto'),
                    (12, 'El Carmen de Atrato'),
                    (12, 'El Litoral del San Juan'),
                    (12, 'Istmina'),
                    (12, 'Juradó'),
                    (12, 'Lloró'),
                    (12, 'Medio Atrato'),
                    (12, 'Medio Baudó'),
                    (12, 'Medio San Juan'),
                    (12, 'Nóvita'),
                    (12, 'Nuquí'),
                    (12, 'Río Iro'),
                    (12, 'Río Quito'),
                    (12, 'Riosucio'),
                    (12, 'San José del Palmar'),
                    (12, 'Sipí'),
                    (12, 'Tadó'),
                    (12, 'Unguía'),
                    (12, 'Unión Panamericana'),
                    (17, 'Acevedo'),
                    (17, 'Agrado'),
                    (17, 'Aipe'),
                    (17, 'Algeciras'),
                    (17, 'Altamira'),
                    (17, 'Baraya'),
                    (17, 'Campoalegre'),
                    (17, 'Colombia'),
                    (17, 'Elías'),
                    (17, 'Garzón'),
                    (17, 'Gigante'),
                    (17, 'Guadalupe'),
                    (17, 'Hobo'),
                    (17, 'Iquira'),
                    (17, 'Isnos'),
                    (17, 'La Argentina'),
                    (17, 'La Plata'),
                    (17, 'Nátaga'),
                    (17, 'Oporapa'),
                    (17, 'Paicol'),
                    (17, 'Palermo'),
                    (17, 'Palestina'),
                    (17, 'Pital'),
                    (17, 'Pitalito'),
                    (17, 'Rivera'),
                    (17, 'Saladoblanco'),
                    (17, 'San Agustín'),
                    (17, 'Santa María'),
                    (17, 'Suaza'),
                    (17, 'Tarqui'),
                    (17, 'Tesalia'),
                    (17, 'Tello'),
                    (17, 'Teruel'),
                    (17, 'Timaná'),
                    (17, 'Villavieja'),
                    (17, 'Yaguará'),
                    (18, 'Albania'),
                    (18, 'Barrancas'),
                    (18, 'Dibula'),
                    (18, 'Distracción'),
                    (18, 'El Molino'),
                    (18, 'Fonseca'),
                    (18, 'Hatonuevo'),
                    (18, 'La Jagua del Pilar'),
                    (18, 'Maicao'),
                    (18, 'Manaure'),
                    (18, 'San Juan del Cesar'),
                    (18, 'Uribia'),
                    (18, 'Urumita'),
                    (18, 'Villanueva'),
                    (19, 'Algarrobo'),
                    (19, 'Aracataca'),
                    (19, 'Ariguaní'),
                    (19, 'Cerro San Antonio'),
                    (19, 'Chivolo'),
                    (19, 'Ciénaga'),
                    (19, 'Concordia'),
                    (19, 'El Banco'),
                    (19, 'El Piñon'),
                    (19, 'El Retén'),
                    (19, 'Fundación'),
                    (19, 'Guamal'),
                    (19, 'Nueva Granada'),
                    (19, 'Pedraza'),
                    (19, 'Pijiño del Carmen'),
                    (19, 'Pivijay'),
                    (19, 'Plato'),
                    (19, 'Pueblo Viejo'),
                    (19, 'Remolino'),
                    (19, 'Sabanas de San Angel'),
                    (19, 'Salamina'),
                    (19, 'San Sebastián de Buenavista'),
                    (19, 'San Zenón'),
                    (19, 'Santa Ana'),
                    (19, 'Santa Bárbara de Pinto'),
                    (19, 'Sitionuevo'),
                    (19, 'Tenerife'),
                    (19, 'Zapayán'),
                    (19, 'Zona Bananera'),
                    (20, 'Acacias'),
                    (20, 'Barranca de Upía'),
                    (20, 'Cabuyaro'),
                    (20, 'Castilla la Nueva'),
                    (20, 'Cubarral'),
                    (20, 'Cumaral'),
                    (20, 'El Calvario'),
                    (20, 'El Castillo'),
                    (20, 'El Dorado'),
                    (20, 'Fuente de Oro'),
                    (20, 'Granada'),
                    (20, 'Guamal'),
                    (20, 'Mapiripán'),
                    (20, 'Mesetas'),
                    (20, 'La Macarena'),
                    (20, 'Uribe'),
                    (20, 'Lejanías'),
                    (20, 'Puerto Concordia'),
                    (20, 'Puerto Gaitán'),
                    (20, 'Puerto López'),
                    (20, 'Puerto Lleras'),
                    (20, 'Puerto Rico'),
                    (20, 'Restrepo'),
                    (20, 'San Carlos de Guaroa'),
                    (20, 'San Juan de Arama'),
                    (20, 'San Juanito'),
                    (20, 'San Martín'),
                    (20, 'Vista Hermosa'),
                    (21, 'Albán'),
                    (21, 'Aldana'),
                    (21, 'Ancuyá'),
                    (21, 'Arboleda'),
                    (21, 'Barbacoas'),
                    (21, 'Belén'),
                    (21, 'Buesaco'),
                    (21, 'Colón'),
                    (21, 'Consaca'),
                    (21, 'Contadero'),
                    (21, 'Córdoba'),
                    (21, 'Cuaspud'),
                    (21, 'Cumbal'),
                    (21, 'Cumbitara'),
                    (21, 'Chachagüí'),
                    (21, 'El Charco'),
                    (21, 'El Peñol'),
                    (21, 'El Rosario'),
                    (21, 'El Tablón de Gómez'),
                    (21, 'El Tambo'),
                    (21, 'Funes'),
                    (21, 'Guachucal'),
                    (21, 'Guaitarilla'),
                    (21, 'Gualmatán'),
                    (21, 'Iles'),
                    (21, 'Imués'),
                    (21, 'Ipiales'),
                    (21, 'La Cruz'),
                    (21, 'La Florida'),
                    (21, 'La Llanada'),
                    (21, 'La Tola'),
                    (21, 'La Unión'),
                    (21, 'Leiva'),
                    (21, 'Linares'),
                    (21, 'Los Andes'),
                    (21, 'Magüí'),
                    (21, 'Mallama'),
                    (21, 'Mosquera'),
                    (21, 'Nariño'),
                    (21, 'Olaya Herrera'),
                    (21, 'Ospina'),
                    (21, 'Francisco Pizarro'),
                    (21, 'Policarpa'),
                    (21, 'Potosí'),
                    (21, 'Providencia'),
                    (21, 'Puerres'),
                    (21, 'Pupiales'),
                    (21, 'Ricaurte'),
                    (21, 'Roberto Payán'),
                    (21, 'Samaniego'),
                    (21, 'Sandoná'),
                    (21, 'San Bernardo'),
                    (21, 'San Lorenzo'),
                    (21, 'San Pablo'),
                    (21, 'San Pedro de Cartago'),
                    (21, 'Santa Bárbara'),
                    (21, 'Santacruz'),
                    (21, 'Sapuyes'),
                    (21, 'Taminango'),
                    (21, 'Tangua'),
                    (21, 'San Andrés de Tumaco'),
                    (21, 'Túquerres'),
                    (21, 'Yacuanquer'),
                    (22, 'Abrego'),
                    (22, 'Arboledas'),
                    (22, 'Bochalema'),
                    (22, 'Bucarasica'),
                    (22, 'Cácota'),
                    (22, 'Cachirá'),
                    (22, 'Chinácota'),
                    (22, 'Chitagá'),
                    (22, 'Convención'),
                    (22, 'Cucutilla'),
                    (22, 'Durania'),
                    (22, 'El Carmen'),
                    (22, 'El Tarra'),
                    (22, 'El Zulia'),
                    (22, 'Gramalote'),
                    (22, 'Hacarí'),
                    (22, 'Herrán'),
                    (22, 'Labateca'),
                    (22, 'La Esperanza'),
                    (22, 'La Playa'),
                    (22, 'Los Patios'),
                    (22, 'Lourdes'),
                    (22, 'Mutiscua'),
                    (22, 'Ocaña'),
                    (22, 'Pamplona'),
                    (22, 'Pamplonita'),
                    (22, 'Puerto Santander'),
                    (22, 'Ragonvalia'),
                    (22, 'Salazar'),
                    (22, 'San Calixto'),
                    (22, 'San Cayetano'),
                    (22, 'Santiago'),
                    (22, 'Sardinata'),
                    (22, 'Silos'),
                    (22, 'Teorama'),
                    (22, 'Tibú'),
                    (22, 'Toledo'),
                    (22, 'Villa Caro'),
                    (22, 'Villa del Rosario'),
                    (24, 'Buenavista'),
                    (24, 'Calarcá'),
                    (24, 'Circasia'),
                    (24, 'Córdoba'),
                    (24, 'Filandia'),
                    (24, 'Génova'),
                    (24, 'La Tebaida'),
                    (24, 'Montenegro'),
                    (24, 'Pijao'),
                    (24, 'Quimbaya'),
                    (24, 'Salento'),
                    (25, 'Apía'),
                    (25, 'Balboa'),
                    (25, 'Belén de Umbría'),
                    (25, 'Dosquebradas'),
                    (25, 'Guática'),
                    (25, 'La Celia'),
                    (25, 'La Virginia'),
                    (25, 'Marsella'),
                    (25, 'Mistrató'),
                    (25, 'Pueblo Rico'),
                    (25, 'Quinchía'),
                    (25, 'Santa Rosa de Cabal'),
                    (25, 'Santuario'),
                    (27, 'Aguada'),
                    (27, 'Albania'),
                    (27, 'Aratoca'),
                    (27, 'Barbosa'),
                    (27, 'Barichara'),
                    (27, 'Barrancabermeja'),
                    (27, 'Betulia'),
                    (27, 'Bolívar'),
                    (27, 'Cabrera'),
                    (27, 'California'),
                    (27, 'Capitanejo'),
                    (27, 'Carcasí'),
                    (27, 'Cepitá'),
                    (27, 'Cerrito'),
                    (27, 'Charalá'),
                    (27, 'Charta'),
                    (27, 'Chimá'),
                    (27, 'Chipatá'),
                    (27, 'Cimitarra'),
                    (27, 'Concepción'),
                    (27, 'Confines'),
                    (27, 'Contratación'),
                    (27, 'Coromoro'),
                    (27, 'Curití'),
                    (27, 'El Carmen de Chucurí'),
                    (27, 'El Guacamayo'),
                    (27, 'El Peñón'),
                    (27, 'El Playón'),
                    (27, 'Encino'),
                    (27, 'Enciso'),
                    (27, 'Florián'),
                    (27, 'Floridablanca'),
                    (27, 'Galán'),
                    (27, 'Gambita'),
                    (27, 'Girón'),
                    (27, 'Guaca'),
                    (27, 'Guadalupe'),
                    (27, 'Guapotá'),
                    (27, 'Guavatá'),
                    (27, 'Güepsa'),
                    (27, 'Hato'),
                    (27, 'Jesús María'),
                    (27, 'Jordán'),
                    (27, 'La Belleza'),
                    (27, 'Landázuri'),
                    (27, 'La Paz'),
                    (27, 'Lebríja'),
                    (27, 'Los Santos'),
                    (27, 'Macaravita'),
                    (27, 'Málaga'),
                    (27, 'Matanza'),
                    (27, 'Mogotes'),
                    (27, 'Molagavita'),
                    (27, 'Ocamonte'),
                    (27, 'Oiba'),
                    (27, 'Onzaga'),
                    (27, 'Palmar'),
                    (27, 'Palmas del Socorro'),
                    (27, 'Páramo'),
                    (27, 'Piedecuesta'),
                    (27, 'Pinchote'),
                    (27, 'Puente Nacional'),
                    (27, 'Puerto Parra'),
                    (27, 'Puerto Wilches'),
                    (27, 'Rionegro'),
                    (27, 'Sabana de Torres'),
                    (27, 'San Andrés'),
                    (27, 'San Benito'),
                    (27, 'San Gil'),
                    (27, 'San Joaquín'),
                    (27, 'San José de Miranda'),
                    (27, 'San Miguel'),
                    (27, 'San Vicente de Chucurí'),
                    (27, 'Santa Bárbara'),
                    (27, 'Santa Helena del Opón'),
                    (27, 'Simacota'),
                    (27, 'Socorro'),
                    (27, 'Suaita'),
                    (27, 'Sucre'),
                    (27, 'Suratá'),
                    (27, 'Tona'),
                    (27, 'Valle de San José'),
                    (27, 'Vélez'),
                    (27, 'Vetas'),
                    (27, 'Villanueva'),
                    (27, 'Zapatoca'),
                    (28, 'Buenavista'),
                    (28, 'Caimito'),
                    (28, 'Coloso'),
                    (28, 'Corozal'),
                    (28, 'Coveñas'),
                    (28, 'Chalán'),
                    (28, 'El Roble'),
                    (28, 'Galeras'),
                    (28, 'Guaranda'),
                    (28, 'La Unión')
                ) AS v(DepartamentoId, Nombre) ON m.DepartamentoId = v.DepartamentoId AND m.Nombre = v.Nombre;
            ");

            migrationBuilder.Sql(@"
                DELETE m FROM Municipios m
                INNER JOIN (VALUES
                    (28, 'Los Palmitos'),
                    (28, 'Majagual'),
                    (28, 'Morroa'),
                    (28, 'Ovejas'),
                    (28, 'Palmito'),
                    (28, 'Sampués'),
                    (28, 'San Benito Abad'),
                    (28, 'San Juan de Betulia'),
                    (28, 'San Marcos'),
                    (28, 'San Onofre'),
                    (28, 'San Pedro'),
                    (28, 'San Luis de Sincé'),
                    (28, 'Sucre'),
                    (28, 'Santiago de Tolú'),
                    (28, 'Tolú Viejo'),
                    (29, 'Alpujarra'),
                    (29, 'Alvarado'),
                    (29, 'Ambalema'),
                    (29, 'Anzoátegui'),
                    (29, 'Armero'),
                    (29, 'Ataco'),
                    (29, 'Cajamarca'),
                    (29, 'Carmen de Apicala'),
                    (29, 'Casabianca'),
                    (29, 'Chaparral'),
                    (29, 'Coello'),
                    (29, 'Coyaima'),
                    (29, 'Cunday'),
                    (29, 'Dolores'),
                    (29, 'Espinal'),
                    (29, 'Falan'),
                    (29, 'Flandes'),
                    (29, 'Fresno'),
                    (29, 'Guamo'),
                    (29, 'Herveo'),
                    (29, 'Honda'),
                    (29, 'Icononzo'),
                    (29, 'Lérida'),
                    (29, 'Líbano'),
                    (29, 'Mariquita'),
                    (29, 'Melgar'),
                    (29, 'Murillo'),
                    (29, 'Natagaima'),
                    (29, 'Ortega'),
                    (29, 'Palocabildo'),
                    (29, 'Piedras'),
                    (29, 'Planadas'),
                    (29, 'Prado'),
                    (29, 'Purificación'),
                    (29, 'Rio Blanco'),
                    (29, 'Roncesvalles'),
                    (29, 'Rovira'),
                    (29, 'Saldaña'),
                    (29, 'San Antonio'),
                    (29, 'San Luis'),
                    (29, 'Santa Isabel'),
                    (29, 'Suárez'),
                    (29, 'Valle de San Juan'),
                    (29, 'Venadillo'),
                    (29, 'Villahermosa'),
                    (29, 'Villarrica'),
                    (30, 'Alcalá'),
                    (30, 'Andalucía'),
                    (30, 'Ansermanuevo'),
                    (30, 'Argelia'),
                    (30, 'Bolívar'),
                    (30, 'Buenaventura'),
                    (30, 'Guadalajara de Buga'),
                    (30, 'Bugalagrande'),
                    (30, 'Caicedonia'),
                    (30, 'Calima'),
                    (30, 'Candelaria'),
                    (30, 'Cartago'),
                    (30, 'Dagua'),
                    (30, 'El Águila'),
                    (30, 'El Cairo'),
                    (30, 'El Cerrito'),
                    (30, 'El Dovio'),
                    (30, 'Florida'),
                    (30, 'Ginebra'),
                    (30, 'Guacarí'),
                    (30, 'Jamundí'),
                    (30, 'La Cumbre'),
                    (30, 'La Unión'),
                    (30, 'La Victoria'),
                    (30, 'Obando'),
                    (30, 'Palmira'),
                    (30, 'Pradera'),
                    (30, 'Restrepo'),
                    (30, 'Riofrío'),
                    (30, 'Roldanillo'),
                    (30, 'San Pedro'),
                    (30, 'Sevilla'),
                    (30, 'Toro'),
                    (30, 'Trujillo'),
                    (30, 'Tuluá'),
                    (30, 'Ulloa'),
                    (30, 'Versalles'),
                    (30, 'Vijes'),
                    (30, 'Yotoco'),
                    (30, 'Yumbo'),
                    (30, 'Zarzal'),
                    (3, 'Arauquita'),
                    (3, 'Cravo Norte'),
                    (3, 'Fortul'),
                    (3, 'Puerto Rondón'),
                    (3, 'Saravena'),
                    (3, 'Tame'),
                    (9, 'Aguazul'),
                    (9, 'Chámeza'),
                    (9, 'Hato Corozal'),
                    (9, 'La Salina'),
                    (9, 'Maní'),
                    (9, 'Monterrey'),
                    (9, 'Nunchía'),
                    (9, 'Orocué'),
                    (9, 'Paz de Ariporo'),
                    (9, 'Pore'),
                    (9, 'Recetor'),
                    (9, 'Sabanalarga'),
                    (9, 'Sácama'),
                    (9, 'San Luis de Gaceno'),
                    (9, 'Támara'),
                    (9, 'Tauramena'),
                    (9, 'Trinidad'),
                    (9, 'Villanueva'),
                    (23, 'Colón'),
                    (23, 'Orito'),
                    (23, 'Puerto Asís'),
                    (23, 'Puerto Caicedo'),
                    (23, 'Puerto Guzmán'),
                    (23, 'Leguízamo'),
                    (23, 'Sibundoy'),
                    (23, 'San Francisco'),
                    (23, 'San Miguel'),
                    (23, 'Santiago'),
                    (23, 'Valle de Guamez'),
                    (23, 'Villagarzón'),
                    (26, 'Providencia'),
                    (1, 'El Encanto'),
                    (1, 'La Chorrera'),
                    (1, 'La Pedrera'),
                    (1, 'La Victoria'),
                    (1, 'Miriti Paraná'),
                    (1, 'Puerto Alegría'),
                    (1, 'Puerto Arica'),
                    (1, 'Puerto Nariño'),
                    (1, 'Puerto Santander'),
                    (1, 'Tarapacá'),
                    (15, 'Barranco Minas'),
                    (15, 'Mapiripana'),
                    (15, 'San Felipe'),
                    (15, 'Puerto Colombia'),
                    (15, 'La Guadalupe'),
                    (15, 'Cacahual'),
                    (15, 'Pana Pana'),
                    (15, 'Morichal'),
                    (16, 'Calamar'),
                    (16, 'El Retorno'),
                    (16, 'Miraflores'),
                    (31, 'Caruru'),
                    (31, 'Pacoa'),
                    (31, 'Taraira'),
                    (31, 'Papunaua'),
                    (31, 'Yavaraté'),
                    (32, 'La Primavera'),
                    (32, 'Santa Rosalía'),
                    (32, 'Cumaribo')
                ) AS v(DepartamentoId, Nombre) ON m.DepartamentoId = v.DepartamentoId AND m.Nombre = v.Nombre;
            ");

            migrationBuilder.Sql("DELETE FROM Paises WHERE Nombre <> N'Colombia';");
        }
    }
}
